/*
 * Copyright (c) 2016 Ryan McCullagh <me@ryanmccullagh.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <object.h>
#include <assert.h>

#include "como_ast.h"
#include "como_stack.h"
#include "como_compiler.h"
#include "como_debug.h"
#include "como_opcode.h"
#include "como_globals.h"
#include "como_parser.h"
#include "como_lexer.h"

int yyparse(ast_node **ast, yyscan_t scanner);

int main(int argc, char **argv)
{
    ast_node *program;

    if(argc < 2) 
    {
        fputs(
            "Usage: como FLAGS FILE | como FILE\n"
            "FLAGS\n"
            "    --print-asm    print instructions generated by the compiler\n",
            stdout);

        return 0;
    }
    

    if(argc == 3 && strcmp(argv[1], "--print-asm") == 0) 
    {
        program = como_parse(argv[2]);
        como_dump_asm(program, argv[2]);
    } 
    else 
    {
        program = como_parse(argv[1]);
        como_compile_ast(program, argv[1]);
    }
    
    ast_node_free(program);

    return 0;
}
